postgres:
  host: 192.168.10.73
  port: 30432
  dbname: bifrost_golden_source
  user: bifrost
  password: bifrost_stg

trade_postgres:
  host: 192.168.10.73
  port: 30432
  dbname: bifrost_dev
  token_dbnames:
    - bifrost_dev
    - bifrost_stg
    - bifrost_prod
  user: bifrost
  password: bifrost_stg

golden_source:
  host: 192.168.10.73
  port: 30432
  database: bifrost_golden_source
  user: bifrost
  password: bifrost_stg

worker:
  poll_interval_sec: 5

write_token: ""
