#!/usr/bin/env bash
# Write plugin-local .env from trade-infra PGPASSWORD (gitignored).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFRA_ENV="${BIFROST_TRADE_INFRA_ENV:-$HOME/Desktop/stocks/bifrost-trade-infra/.env}"
OUT="$ROOT/.env"

if [[ ! -f "$INFRA_ENV" ]]; then
  echo "Missing $INFRA_ENV — set PGPASSWORD there or export POSTGRES_PASSWORD." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$INFRA_ENV"
set +a

if [[ -z "${PGPASSWORD:-}" ]]; then
  echo "PGPASSWORD empty in $INFRA_ENV" >&2
  exit 1
fi

cat >"$OUT" <<EOF
# Generated by scripts/sync_dev_env.sh — do not commit.
# Golden Source (flex_ops + brokerage) — never use Trade env POSTGRES_DB here.
POSTGRES_HOST=${POSTGRES_HOST:-192.168.10.73}
POSTGRES_PORT=${POSTGRES_PORT:-30432}
POSTGRES_DB=bifrost_golden_source
POSTGRES_USER=${POSTGRES_USER:-bifrost}
POSTGRES_PASSWORD=${PGPASSWORD}
FLEX_TRADE_PG_HOST=${FLEX_TRADE_PG_HOST:-192.168.10.73}
FLEX_TRADE_PG_PORT=${FLEX_TRADE_PG_PORT:-30432}
FLEX_TRADE_PG_DB=${FLEX_TRADE_PG_DB:-bifrost_dev}
FLEX_TRADE_PG_USER=${FLEX_TRADE_PG_USER:-bifrost}
FLEX_TRADE_PG_PASSWORD=${PGPASSWORD}
EOF

echo "Wrote $OUT (POSTGRES_* + FLEX_TRADE_PG_* from trade-infra PGPASSWORD)."
