apiVersion: v1
kind: ConfigMap
metadata:
  name: flex-query-config
  labels:
    app.kubernetes.io/name: flex-query
data:
  flex-query.yaml: |
    postgres:
      host: bifrost-postgres-rw.data.svc.cluster.local
      port: 5432
      dbname: bifrost_golden_source
      user: bifrost
      password: ""
    trade_postgres:
      host: bifrost-postgres-rw.data.svc.cluster.local
      port: 5432
      dbname: bifrost_dev
      user: bifrost
      password: ""
    golden_source:
      host: bifrost-postgres-rw.data.svc.cluster.local
      port: 5432
      database: bifrost_golden_source
      user: bifrost
      password: ""
    worker:
      poll_interval_sec: 5
    write_token: ""
