apiVersion: v1
kind: Service
metadata:
  name: flex-query-api
  labels:
    app.kubernetes.io/name: flex-query-api
    bifrost.flex-query/role: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flex-query-api
  ports:
    - name: http
      port: 8791
      targetPort: http
      protocol: TCP
